# Generated by Django 6.0.4 on 2026-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
