# Generated by Django 6.0.4 on 2026-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0002_workout_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("push", "Push"),
                    ("pull", "Pull"),
                    ("legs", "Legs"),
                    ("cardio", "Cardio"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
    ]
